[package]
name = "gatewayd"
version = "0.1.0"
edition = "2024"

[dependencies]
gateway-core = { path = "../gateway-core" }
gateway-db = { path = "../gateway-db" }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-aws = { workspace = true }
alloy-signer-local = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
base64 = { workspace = true }
jsonwebtoken = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
aes-gcm = { workspace = true }
hmac = { workspace = true }
hex = { workspace = true }
utoipa = { workspace = true }
qrcode = { workspace = true }
aws-config = { workspace = true }
aws-sdk-sesv2 = { workspace = true }
aws-sdk-kms = { workspace = true }
aws-sdk-s3 = { workspace = true }
pdf-writer = { workspace = true }

[dev-dependencies]
tower = { workspace = true }
rsa = { version = "0.9", features = ["pem"] }
rand_08 = { package = "rand", version = "0.8" }
