output "api_url" { value = "https://${var.domain_name}" }
output "api_ecr_repository_url" { value = aws_ecr_repository.api.repository_url }
output "indexer_ecr_repository_url" { value = aws_ecr_repository.indexer.repository_url }
output "kms_key_arn" { value = aws_kms_key.signer.arn }
output "kms_public_key_note" { value = "AWS KMS exposes the secp256k1 public key via GetPublicKey, not an Ethereum address; derive and independently verify the address before funding." }
output "recovery_kms_key_arn" { value = aws_kms_key.recovery.arn }
output "recovery_kms_public_key_note" { value = "Derive the recovery wallet address from this key's GetPublicKey output (cast wallet address --aws) and verify it independently before setting recovery_address; no task role can sign with it, recovered funds are returned by hand." }
output "database_url_secret_arn" { value = aws_secretsmanager_secret.database_url.arn }
output "rpc_url_secret_arn" { value = aws_secretsmanager_secret.rpc_url.arn }
output "webhook_encryption_key_secret_arn" { value = aws_secretsmanager_secret.webhook_encryption_key.arn }
output "admin_bearer_secret_arn" { value = aws_secretsmanager_secret.admin_bearer.arn }
output "ecs_cluster_name" { value = aws_ecs_cluster.this.name }
output "api_service_name" { value = aws_ecs_service.api.name }
output "indexer_service_name" { value = aws_ecs_service.indexer.name }
output "rds_endpoint" { value = aws_db_instance.this.endpoint }
